name: {{project_name}}
description: {{project_description}}

publish_to: 'none' 

# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.5
  auto_size_text_pk: ^3.0.0

  # State
  bloc: ^8.1.2{{#needs_flutter_bloc}}
  flutter_bloc: ^8.1.3{{/needs_flutter_bloc}}{{#needs_equatable}}
  equatable: ^2.0.5{{/needs_equatable}}{{#needs_hydrated_bloc}}
  hydrated_bloc: ^9.1.1{{/needs_hydrated_bloc}}{{#needs_system_interface_title}}

  # System interface{{/needs_system_interface_title}}{{#needs_path_provider}}
  path_provider: ^2.0.15{{/needs_path_provider}}{{#needs_hive}}
  hive: ^2.2.3
  hive_flutter: ^1.1.0{{/needs_hive}}{{#needs_dio}}
  
  # Network
  dio: ^4.0.6{{/needs_dio}}{{#needs_dartz}}
  
  # Functional Programming
  dartz: ^0.10.1{{/needs_dartz}}{{#needs_code_gen_title}}
  
  # Code Generation{{/needs_code_gen_title}}{{#needs_retrofit}}
  retrofit: ^3.3.1{{/needs_retrofit}}{{#needs_json_annotation}}
  json_annotation: ^4.8.1{{/needs_json_annotation}}{{#needs_firebase_title}}
  
  # Firebase{{/needs_firebase_title}}{{#needs_firebase_core}}
  firebase_core: ^2.14.0{{/needs_firebase_core}}{{#needs_firebase_auth}}
  firebase_auth: ^4.6.3{{/needs_firebase_auth}}{{#needs_firebase_remote_config}}
  firebase_remote_config: ^4.2.3{{/needs_firebase_remote_config}}{{#needs_firebase_crashlytics}}
  firebase_crashlytics: ^3.3.3{{/needs_firebase_crashlytics}}{{#needs_firebase_dynamic_links}}
  firebase_dynamic_links: ^5.3.3{{/needs_firebase_dynamic_links}}

  # Navigation
  auto_route: ^7.4.0

  # Dependency Injection
  injectable: ^2.1.2
  get_it: ^7.6.0

  # Localizations
  easy_localization: ^3.0.2

  # Widgets
  shimmer: ^3.0.0{{#needs_flutter_styled_toast}}
  flutter_styled_toast: ^2.1.3{{/needs_flutter_styled_toast}}{{#needs_features_title}}

  # Features{{/needs_features_title}}{{#needs_share_plus}}
  share_plus: ^6.2.0{{/needs_share_plus}}

  # Own
  neon_core:
    git: 
      url: git@github.com:NEON-Software-Solutions/neon_flutter_packages.git
      path: neon_core
      ref: main{{#needs_firebase_remote_config}}

  firebase_remote_config_localization_loader:
    git: 
        url: git@github.com:NEON-Software-Solutions/neon_flutter_packages.git
        path: firebase_remote_config_localization_loader
        ref: main{{/needs_firebase_remote_config}}

  # Logging
  logger: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  analyzer: ^5.13.0  
  flutter_lints: ^2.0.1
  test: ^1.9.4{{#needs_bloc_test}}
  bloc_test: ^9.1.0{{/needs_bloc_test}}{{#needs_mocktail}}
  mocktail: ^0.3.0{{/needs_mocktail}}
  build_runner: ^2.4.5  
  freezed: ^2.3.5
  injectable_generator: ^2.1.6
  json_serializable: ^6.7.0
  flutter_launcher_icons: "^0.13.1"
  flutter_native_splash: ^2.3.1
  auto_route_generator: ^7.1.1{{#needs_retrofit}}
  retrofit_generator: ^4.2.0{{/needs_retrofit}}

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/img/launcher_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
    - assets/img/

  fonts:
    - family: SF-Pro
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Bold.otf
          weight: 700
        - asset: assets/fonts/SF-Pro-Display-Regular.otf
          weight: 400
        - asset: assets/fonts/SF-Pro-Display-RegularItalic.otf
          style: italic