name: CLI_bricks
description: All the bricks used within the CLI
version: 1.0.0
homepage: https://github.com/NEON-Software-Solutions/NEON_bricks/tree/migrate_bricks_to_git/cli_bricks

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  mason: ^0.1.0-dev.49
  path: ^1.8.2